import React from "react";
import SkillButton from "./skillbutton";
import SkillText from "./skilltext";

const SkillTreeFighterOff = props => {
  return (
    <table className="table w-auto">
      <tbody>
        <tr>
          <td className="table-dark">LV1</td>
          <td>
            <SkillText
              skillname="hammer"
              skilltree={props.skilltree}
              getSkillModText={props.getSkillModText}
              getSkillPoints={props.getSkillPoints}
              getSkillId={props.getSkillId}
            />
          </td>
          <td>
            <SkillButton
              skilltreeindex={props.getSkillIndex("hammer")}
              checkAllSkillDeps={props.checkAllSkillDeps}
              checkPrestigeSkill={props.checkPrestigeSkill}
              handleSkillPoint={props.handleSkillPoint}
            />
          </td>
          <td></td>
          <td></td>
          <td></td>
          <td>
            <SkillText
              skillname="sword"
              skilltree={props.skilltree}
              getSkillModText={props.getSkillModText}
              getSkillPoints={props.getSkillPoints}
              getSkillId={props.getSkillId}
            />
          </td>
          <td>
            <SkillButton
              skilltreeindex={props.getSkillIndex("sword")}
              checkAllSkillDeps={props.checkAllSkillDeps}
              checkPrestigeSkill={props.checkPrestigeSkill}
              handleSkillPoint={props.handleSkillPoint}
            />
          </td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td>
            <SkillText
              skillname="archery"
              skilltree={props.skilltree}
              getSkillModText={props.getSkillModText}
              getSkillPoints={props.getSkillPoints}
              getSkillId={props.getSkillId}
            />
          </td>
          <td>
            <SkillButton
              skilltreeindex={props.getSkillIndex("archery")}
              checkAllSkillDeps={props.checkAllSkillDeps}
              checkPrestigeSkill={props.checkPrestigeSkill}
              handleSkillPoint={props.handleSkillPoint}
            />
          </td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td className="table-dark">LV3</td>
          <td>
            <SkillText
              skillname="axe"
              skilltree={props.skilltree}
              getSkillModText={props.getSkillModText}
              getSkillPoints={props.getSkillPoints}
              getSkillId={props.getSkillId}
            />
          </td>
          <td>
            <SkillButton
              skilltreeindex={props.getSkillIndex("axe")}
              checkAllSkillDeps={props.checkAllSkillDeps}
              checkPrestigeSkill={props.checkPrestigeSkill}
              handleSkillPoint={props.handleSkillPoint}
            />
          </td>
          <td></td>
          <td></td>
          <td></td>
          <td>
            <SkillText
              skillname="spear"
              skilltree={props.skilltree}
              getSkillModText={props.getSkillModText}
              getSkillPoints={props.getSkillPoints}
              getSkillId={props.getSkillId}
            />
          </td>
          <td>
            <SkillButton
              skilltreeindex={props.getSkillIndex("spear")}
              checkAllSkillDeps={props.checkAllSkillDeps}
              checkPrestigeSkill={props.checkPrestigeSkill}
              handleSkillPoint={props.handleSkillPoint}
            />
          </td>
          <td></td>
          <td></td>
          <td></td>
          <td>
            <SkillText
              skillname="hunt"
              skilltree={props.skilltree}
              getSkillModText={props.getSkillModText}
              getSkillPoints={props.getSkillPoints}
              getSkillId={props.getSkillId}
            />
          </td>
          <td>
            <SkillButton
              skilltreeindex={props.getSkillIndex("hunt")}
              checkAllSkillDeps={props.checkAllSkillDeps}
              checkPrestigeSkill={props.checkPrestigeSkill}
              handleSkillPoint={props.handleSkillPoint}
            />
          </td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td className="table-dark">LV5</td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td>
            <SkillText
              skillname="melee"
              skilltree={props.skilltree}
              getSkillModText={props.getSkillModText}
              getSkillPoints={props.getSkillPoints}
              getSkillId={props.getSkillId}
            />
          </td>
          <td>
            <SkillButton
              skilltreeindex={props.getSkillIndex("melee")}
              checkAllSkillDeps={props.checkAllSkillDeps}
              checkPrestigeSkill={props.checkPrestigeSkill}
              handleSkillPoint={props.handleSkillPoint}
            />
          </td>
          <td></td>
          <td></td>
          <td></td>
          <td>
            <SkillText
              skillname="track"
              skilltree={props.skilltree}
              getSkillModText={props.getSkillModText}
              getSkillPoints={props.getSkillPoints}
              getSkillId={props.getSkillId}
            />
          </td>
          <td>
            <SkillButton
              skilltreeindex={props.getSkillIndex("track")}
              checkAllSkillDeps={props.checkAllSkillDeps}
              checkPrestigeSkill={props.checkPrestigeSkill}
              handleSkillPoint={props.handleSkillPoint}
            />
          </td>

          <td>
            <SkillText
              skillname="aim"
              skilltree={props.skilltree}
              getSkillModText={props.getSkillModText}
              getSkillPoints={props.getSkillPoints}
              getSkillId={props.getSkillId}
            />
          </td>
          <td>
            <SkillButton
              skilltreeindex={props.getSkillIndex("aim")}
              checkAllSkillDeps={props.checkAllSkillDeps}
              checkPrestigeSkill={props.checkPrestigeSkill}
              handleSkillPoint={props.handleSkillPoint}
            />
          </td>
          <td></td>
        </tr>
        <tr>
          <td className="table-dark">LV10</td>
          <td>
            <SkillText
              skillname="mine"
              skilltree={props.skilltree}
              getSkillModText={props.getSkillModText}
              getSkillPoints={props.getSkillPoints}
              getSkillId={props.getSkillId}
            />
          </td>
          <td>
            <SkillButton
              skilltreeindex={props.getSkillIndex("mine")}
              checkAllSkillDeps={props.checkAllSkillDeps}
              checkPrestigeSkill={props.checkPrestigeSkill}
              handleSkillPoint={props.handleSkillPoint}
            />
          </td>
          <td></td>
          <td></td>
          <td></td>
          <td>
            <SkillText
              skillname="injure"
              skilltree={props.skilltree}
              getSkillModText={props.getSkillModText}
              getSkillPoints={props.getSkillPoints}
              getSkillId={props.getSkillId}
            />
          </td>
          <td>
            <SkillButton
              skilltreeindex={props.getSkillIndex("injure")}
              checkAllSkillDeps={props.checkAllSkillDeps}
              checkPrestigeSkill={props.checkPrestigeSkill}
              handleSkillPoint={props.handleSkillPoint}
            />
          </td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td>
            <SkillText
              skillname="pierce"
              skilltree={props.skilltree}
              getSkillModText={props.getSkillModText}
              getSkillPoints={props.getSkillPoints}
              getSkillId={props.getSkillId}
            />
          </td>
          <td>
            <SkillButton
              skilltreeindex={props.getSkillIndex("pierce")}
              checkAllSkillDeps={props.checkAllSkillDeps}
              checkPrestigeSkill={props.checkPrestigeSkill}
              handleSkillPoint={props.handleSkillPoint}
            />
          </td>
          <td></td>
        </tr>
        <tr>
          <td className="table-dark">LV15</td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td className="table-danger">
            <SkillText
              skillname="cleave"
              skilltree={props.skilltree}
              getSkillModText={props.getSkillModText}
              getSkillPoints={props.getSkillPoints}
              getSkillId={props.getSkillId}
            />
          </td>
          <td>
            <SkillButton
              skilltreeindex={props.getSkillIndex("cleave")}
              checkAllSkillDeps={props.checkAllSkillDeps}
              checkPrestigeSkill={props.checkPrestigeSkill}
              handleSkillPoint={props.handleSkillPoint}
            />
          </td>
          <td></td>
          <td>
            <SkillText
              skillname="stun"
              skilltree={props.skilltree}
              getSkillModText={props.getSkillModText}
              getSkillPoints={props.getSkillPoints}
              getSkillId={props.getSkillId}
            />
          </td>
          <td>
            <SkillButton
              skilltreeindex={props.getSkillIndex("stun")}
              checkAllSkillDeps={props.checkAllSkillDeps}
              checkPrestigeSkill={props.checkPrestigeSkill}
              handleSkillPoint={props.handleSkillPoint}
            />
          </td>
          <td></td>
          <td></td>
          <td></td>
          <td>
            <SkillText
              skillname="stack"
              skilltree={props.skilltree}
              getSkillModText={props.getSkillModText}
              getSkillPoints={props.getSkillPoints}
              getSkillId={props.getSkillId}
            />
          </td>
          <td>
            <SkillButton
              skilltreeindex={props.getSkillIndex("stack")}
              checkAllSkillDeps={props.checkAllSkillDeps}
              checkPrestigeSkill={props.checkPrestigeSkill}
              handleSkillPoint={props.handleSkillPoint}
            />
          </td>
          <td></td>
        </tr>
        <tr>
          <td className="table-dark">LV20</td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td className="table-danger">
            <SkillText
              skillname="smith"
              skilltree={props.skilltree}
              getSkillModText={props.getSkillModText}
              getSkillPoints={props.getSkillPoints}
              getSkillId={props.getSkillId}
            />
          </td>
          <td>
            <SkillButton
              skilltreeindex={props.getSkillIndex("smith")}
              checkAllSkillDeps={props.checkAllSkillDeps}
              checkPrestigeSkill={props.checkPrestigeSkill}
              handleSkillPoint={props.handleSkillPoint}
            />
          </td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td>
            <SkillText
              skillname="volley"
              skilltree={props.skilltree}
              getSkillModText={props.getSkillModText}
              getSkillPoints={props.getSkillPoints}
              getSkillId={props.getSkillId}
            />
          </td>
          <td>
            <SkillButton
              skilltreeindex={props.getSkillIndex("volley")}
              checkAllSkillDeps={props.checkAllSkillDeps}
              checkPrestigeSkill={props.checkPrestigeSkill}
              handleSkillPoint={props.handleSkillPoint}
            />
          </td>
          <td></td>
        </tr>
      </tbody>
    </table>
  );
};

export default SkillTreeFighterOff;
