import React from "react";
import SkillButton from "./skillbutton";
import SkillText from "./skilltext";

const SkillTreeClericPray = props => {
  return (
    <table className="table" style={{ width: 1200 }}>
      <tbody>
        <tr>
          <td className="table-dark">LV1</td>
          <td>
            <SkillText
              skillname="aid"
              skilltree={props.skilltree}
              getSkillModText={props.getSkillModText}
              getSkillPoints={props.getSkillPoints}
              getSkillId={props.getSkillId}
            />
          </td>
          <td>
            <SkillButton
              skilltreeindex={props.getSkillIndex("aid")}
              checkAllSkillDeps={props.checkAllSkillDeps}
              handleSkillPoint={props.handleSkillPoint}
            />
          </td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td>
            <SkillText
              skillname="pray"
              skilltree={props.skilltree}
              getSkillModText={props.getSkillModText}
              getSkillPoints={props.getSkillPoints}
              getSkillId={props.getSkillId}
            />
          </td>
          <td>
            <SkillButton
              skilltreeindex={props.getSkillIndex("pray")}
              checkAllSkillDeps={props.checkAllSkillDeps}
              handleSkillPoint={props.handleSkillPoint}
            />
          </td>
          <td></td>
          <td></td>
          <td>
            <SkillText
              skillname="war"
              skilltree={props.skilltree}
              getSkillModText={props.getSkillModText}
              getSkillPoints={props.getSkillPoints}
              getSkillId={props.getSkillId}
            />
          </td>
          <td>
            <SkillButton
              skilltreeindex={props.getSkillIndex("war")}
              checkAllSkillDeps={props.checkAllSkillDeps}
              handleSkillPoint={props.handleSkillPoint}
            />
          </td>
          <td></td>
        </tr>
        <tr>
          <td className="table-dark">LV3</td>
          <td>
            <SkillText
              skillname="heal"
              skilltree={props.skilltree}
              getSkillModText={props.getSkillModText}
              getSkillPoints={props.getSkillPoints}
              getSkillId={props.getSkillId}
            />
          </td>
          <td>
            <SkillButton
              skilltreeindex={props.getSkillIndex("heal")}
              checkAllSkillDeps={props.checkAllSkillDeps}
              handleSkillPoint={props.handleSkillPoint}
            />
          </td>
          <td></td>
          <td>
            <SkillText
              skillname="light"
              skilltree={props.skilltree}
              getSkillModText={props.getSkillModText}
              getSkillPoints={props.getSkillPoints}
              getSkillId={props.getSkillId}
            />
          </td>
          <td>
            <SkillButton
              skilltreeindex={props.getSkillIndex("light")}
              checkAllSkillDeps={props.checkAllSkillDeps}
              handleSkillPoint={props.handleSkillPoint}
            />
          </td>
          <td></td>
          <td>
            <SkillText
              skillname="water"
              skilltree={props.skilltree}
              getSkillModText={props.getSkillModText}
              getSkillPoints={props.getSkillPoints}
              getSkillId={props.getSkillId}
            />
          </td>
          <td>
            <SkillButton
              skilltreeindex={props.getSkillIndex("water")}
              checkAllSkillDeps={props.checkAllSkillDeps}
              handleSkillPoint={props.handleSkillPoint}
            />
          </td>
          <td></td>
          <td></td>
          <td>
            <SkillText
              skillname="dark"
              skilltree={props.skilltree}
              getSkillModText={props.getSkillModText}
              getSkillPoints={props.getSkillPoints}
              getSkillId={props.getSkillId}
            />
          </td>
          <td>
            <SkillButton
              skilltreeindex={props.getSkillIndex("dark")}
              checkAllSkillDeps={props.checkAllSkillDeps}
              handleSkillPoint={props.handleSkillPoint}
            />
          </td>
          <td></td>
        </tr>
        <tr>
          <td className="table-dark">LV5</td>
          <td></td>
          <td>
            <SkillText
              skillname="bless"
              skilltree={props.skilltree}
              getSkillModText={props.getSkillModText}
              getSkillPoints={props.getSkillPoints}
              getSkillId={props.getSkillId}
            />
          </td>
          <td>
            <SkillButton
              skilltreeindex={props.getSkillIndex("bless")}
              checkAllSkillDeps={props.checkAllSkillDeps}
              handleSkillPoint={props.handleSkillPoint}
            />
          </td>
          <td></td>
          <td>
            <SkillText
              skillname="cure"
              skilltree={props.skilltree}
              getSkillModText={props.getSkillModText}
              getSkillPoints={props.getSkillPoints}
              getSkillId={props.getSkillId}
            />
          </td>
          <td>
            <SkillButton
              skilltreeindex={props.getSkillIndex("cure")}
              checkAllSkillDeps={props.checkAllSkillDeps}
              handleSkillPoint={props.handleSkillPoint}
            />
          </td>
          <td></td>
          <td>
            <SkillText
              skillname="rain"
              skilltree={props.skilltree}
              getSkillModText={props.getSkillModText}
              getSkillPoints={props.getSkillPoints}
              getSkillId={props.getSkillId}
            />
          </td>
          <td>
            <SkillButton
              skilltreeindex={props.getSkillIndex("rain")}
              checkAllSkillDeps={props.checkAllSkillDeps}
              handleSkillPoint={props.handleSkillPoint}
            />
          </td>
          <td></td>
          <td>
            <SkillText
              skillname="curse"
              skilltree={props.skilltree}
              getSkillModText={props.getSkillModText}
              getSkillPoints={props.getSkillPoints}
              getSkillId={props.getSkillId}
            />
          </td>
          <td>
            <SkillButton
              skilltreeindex={props.getSkillIndex("curse")}
              checkAllSkillDeps={props.checkAllSkillDeps}
              handleSkillPoint={props.handleSkillPoint}
            />
          </td>
          <td></td>
        </tr>
        <tr>
          <td className="table-dark">LV10</td>
          <td></td>
          <td></td>
          <td>
            <SkillText
              skillname="banish"
              skilltree={props.skilltree}
              getSkillModText={props.getSkillModText}
              getSkillPoints={props.getSkillPoints}
              getSkillId={props.getSkillId}
            />
          </td>
          <td>
            <SkillButton
              skilltreeindex={props.getSkillIndex("banish")}
              checkAllSkillDeps={props.checkAllSkillDeps}
              handleSkillPoint={props.handleSkillPoint}
            />
          </td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td>
            <SkillText
              skillname="dispel"
              skilltree={props.skilltree}
              getSkillModText={props.getSkillModText}
              getSkillPoints={props.getSkillPoints}
              getSkillId={props.getSkillId}
            />
          </td>
          <td>
            <SkillButton
              skilltreeindex={props.getSkillIndex("dispel")}
              checkAllSkillDeps={props.checkAllSkillDeps}
              handleSkillPoint={props.handleSkillPoint}
            />
          </td>
          <td></td>
        </tr>
        <tr>
          <td className="table-dark">LV15</td>
          <td className="table-danger">
            <SkillText
              skillname="flame"
              skilltree={props.skilltree}
              getSkillModText={props.getSkillModText}
              getSkillPoints={props.getSkillPoints}
              getSkillId={props.getSkillId}
            />
          </td>
          <td>
            <SkillButton
              skilltreeindex={props.getSkillIndex("flame")}
              checkAllSkillDeps={props.checkAllSkillDeps}
              handleSkillPoint={props.handleSkillPoint}
            />
          </td>
          <td style={{ backgroundColor: "#EE82EE" }}>
            <SkillText
              skillname="exorcism"
              skilltree={props.skilltree}
              getSkillModText={props.getSkillModText}
              getSkillPoints={props.getSkillPoints}
              getSkillId={props.getSkillId}
            />
          </td>
          <td>
            <SkillButton
              skilltreeindex={props.getSkillIndex("exorcism")}
              checkAllSkillDeps={props.checkAllSkillDeps}
              handleSkillPoint={props.handleSkillPoint}
            />
          </td>
          <td>
            <SkillText
              skillname="mass_cure"
              skilltree={props.skilltree}
              getSkillModText={props.getSkillModText}
              getSkillPoints={props.getSkillPoints}
              getSkillId={props.getSkillId}
            />
          </td>
          <td>
            <SkillButton
              skilltreeindex={props.getSkillIndex("mass_cure")}
              checkAllSkillDeps={props.checkAllSkillDeps}
              handleSkillPoint={props.handleSkillPoint}
            />
          </td>
          <td></td>
          <td style={{ backgroundColor: "#EE82EE" }}>
            <SkillText
              skillname="summon"
              skilltree={props.skilltree}
              getSkillModText={props.getSkillModText}
              getSkillPoints={props.getSkillPoints}
              getSkillId={props.getSkillId}
            />
          </td>
          <td>
            <SkillButton
              skilltreeindex={props.getSkillIndex("summon")}
              checkAllSkillDeps={props.checkAllSkillDeps}
              handleSkillPoint={props.handleSkillPoint}
            />
          </td>
          <td>
            <SkillText
              skillname="raise"
              skilltree={props.skilltree}
              getSkillModText={props.getSkillModText}
              getSkillPoints={props.getSkillPoints}
              getSkillId={props.getSkillId}
            />
          </td>
          <td>
            <SkillButton
              skilltreeindex={props.getSkillIndex("raise")}
              checkAllSkillDeps={props.checkAllSkillDeps}
              handleSkillPoint={props.handleSkillPoint}
            />
          </td>
          <td>
            <SkillText
              skillname="leech"
              skilltree={props.skilltree}
              getSkillModText={props.getSkillModText}
              getSkillPoints={props.getSkillPoints}
              getSkillId={props.getSkillId}
            />
          </td>
          <td>
            <SkillButton
              skilltreeindex={props.getSkillIndex("leech")}
              checkAllSkillDeps={props.checkAllSkillDeps}
              handleSkillPoint={props.handleSkillPoint}
            />
          </td>
        </tr>
        <tr>
          <td className="table-dark">LV20</td>
          <td className="table-danger">
            <SkillText
              skillname="aura"
              skilltree={props.skilltree}
              getSkillModText={props.getSkillModText}
              getSkillPoints={props.getSkillPoints}
              getSkillId={props.getSkillId}
            />
          </td>
          <td>
            <SkillButton
              skilltreeindex={props.getSkillIndex("aura")}
              checkAllSkillDeps={props.checkAllSkillDeps}
              handleSkillPoint={props.handleSkillPoint}
            />
          </td>
          <td style={{ backgroundColor: "#EE82EE" }}>
            <SkillText
              skillname="holy"
              skilltree={props.skilltree}
              getSkillModText={props.getSkillModText}
              getSkillPoints={props.getSkillPoints}
              getSkillId={props.getSkillId}
            />
          </td>
          <td>
            <SkillButton
              skilltreeindex={props.getSkillIndex("holy")}
              checkAllSkillDeps={props.checkAllSkillDeps}
              handleSkillPoint={props.handleSkillPoint}
            />
          </td>
          <td>
            <SkillText
              skillname="regen"
              skilltree={props.skilltree}
              getSkillModText={props.getSkillModText}
              getSkillPoints={props.getSkillPoints}
              getSkillId={props.getSkillId}
            />
          </td>
          <td>
            <SkillButton
              skilltreeindex={props.getSkillIndex("regen")}
              checkAllSkillDeps={props.checkAllSkillDeps}
              handleSkillPoint={props.handleSkillPoint}
            />
          </td>
          <td></td>
          <td style={{ backgroundColor: "#EE82EE" }}>
            <SkillText
              skillname="acid_rain"
              skilltree={props.skilltree}
              getSkillModText={props.getSkillModText}
              getSkillPoints={props.getSkillPoints}
              getSkillId={props.getSkillId}
            />
          </td>
          <td>
            <SkillButton
              skilltreeindex={props.getSkillIndex("acid_rain")}
              checkAllSkillDeps={props.checkAllSkillDeps}
              handleSkillPoint={props.handleSkillPoint}
            />
          </td>
          <td className="table-primary">
            <SkillText
              skillname="necromancy"
              skilltree={props.skilltree}
              getSkillModText={props.getSkillModText}
              getSkillPoints={props.getSkillPoints}
              getSkillId={props.getSkillId}
            />
          </td>
          <td>
            <SkillButton
              skilltreeindex={props.getSkillIndex("necromancy")}
              checkAllSkillDeps={props.checkAllSkillDeps}
              handleSkillPoint={props.handleSkillPoint}
            />
          </td>
          <td>
            <SkillText
              skillname="force"
              skilltree={props.skilltree}
              getSkillModText={props.getSkillModText}
              getSkillPoints={props.getSkillPoints}
              getSkillId={props.getSkillId}
            />
          </td>
          <td>
            <SkillButton
              skilltreeindex={props.getSkillIndex("force")}
              checkAllSkillDeps={props.checkAllSkillDeps}
              handleSkillPoint={props.handleSkillPoint}
            />
          </td>
        </tr>
      </tbody>
    </table>
  );
};

export default SkillTreeClericPray;
